version: "3.9"
services:
  deploy:
    depends_on:
      - postgres
    container_name: deployLibraryProject
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9090:9090"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db_library:5432/db_library
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=12345
  postgres:
    container_name: db_library
    image: postgres
    environment:
      POSTGRES_DB: "db_library"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "12345"
    ports:
      - "5432:5432"
